server:
  port: 8083

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: payment_db

    open-in-view: false

  jackson:
    serialization:
      indent-output: true

logging:
  file:
    name: logs/payment-service.log

  level:
    root: INFO
    payment.system.app: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    io.github.resilience4j.circuitbreaker: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [requestId=%X{requestId}] [txnRef=%X{transactionRef}] [txnId=%X{transactionId}] %logger{36} - %msg%n"

    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [requestId=%X{requestId}] [txnRef=%X{transactionRef}] [txnId=%X{transactionId}] %logger{36} - %msg%n"

wallet:
  service:
    base-url: ${WALLET_SERVICE_URL:http://localhost:8084}
    connect-timeout: 5000
    read-timeout: 10000

jwt:
  secret-base64: ${JWT_SECRET_BASE64:"lf8pg3dCyON+2Zv7t98MZ42yh2xaXOUYL+YqLjcx+sg="}
  issuer: ${JWT_ISSUER:payment-user-service}
  audience: ${JWT_AUDIENCE:payment-platform}

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      walletService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

        recordExceptions:
          - org.springframework.web.client.ResourceAccessException
          - payment.system.app.exception.WalletServiceException

        ignoreExceptions:
          - payment.system.app.exception.BadRequestException