server:
  port: 8083

spring:

  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:

    hibernate:
      ddl-auto: update

    show-sql: true

    properties:

      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    open-in-view: false

  jackson:
    serialization:
      indent-output: true

logging:

  level:

    root: INFO

    payment.system.app: DEBUG

    org.springframework.web: INFO

    org.hibernate.SQL: DEBUG

    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

wallet:
  service:
    base-url: http://localhost:8082

management:

  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always